### ISSUE TITLE
I'm

### ISSUE THREAD

**Issue by H3ssn22** [H3ssn22/H2AD20410#3]
```
# Steps represent a sequence of tasks that will be executed as part of the job
steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - uses: actions/checkout@v3

  # Runs a single command using the runners shell
  - name: Run a one-line script
    run: echo Hello, world!

  # Runs a set of commands using the runners shell
  - name: Run a multi-line script
    run: |
      echo Add other actions to build,
      echo test, and deploy your project.
```
